import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "react-hot-toast";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import PageWrapper from "@/components/PageWrapper";
import SidebarToggleButton from "@/components/SidebarToggleButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className + 'max-h-screen'}>
				{" "}
				<ThemeProvider
					attribute="class"
					defaultTheme="light"
					enableSystem
					disableTransitionOnChange
				>
					{/* <Toaster /> */}
					<SidebarToggleButton />
					<Sidebar />
					<div className="flex flex-col h-screen w-full">
						<Header />
						<PageWrapper children={children} />
					</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
